/imu_ros2_node:
  ros__parameters:
    accel_calibbias_x: 0
    accel_calibbias_y: 0
    accel_calibbias_z: 0
    anglvel_calibbias_x: 0
    anglvel_calibbias_y: 0
    anglvel_calibbias_z: 0
    filter_size: 0
    internal_sensor_bandwidth: 0
    point_of_percussion_alignment: 1
    linear_acceleration_compensation: 1
    sampling_frequency: 2000.0
    command_to_execute: no_command
    measured_data_topic_selection: 3
