name: Build ROS2 package

env:
  DEVICE_ID: adis16505-2
  PACKAGE_NAME: "adi_imu"

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - humble
      - humble-develop
      - main

jobs:
  build-package:
    name: ROS ${{ matrix.ros_distribution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
        include:
          # Humble Hawksbill (May 2022 - May 2027) - Ubuntu 22.04 (Jammy)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Setup workspace
        run: mkdir -p ros_ws/src

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ros2_ws/src

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
          use-ros2-testing: false

      - name: Build the package
        id: action_ros_ci_step
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true # TODO: Enable tests if any (TBD)
          import-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Store the build logs
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always() # upload the logs even when the build fails
