name: Lint ROS2 package

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - "*humble*"
  push:
    branches:
      - "*humble*"

env:
  PACKAGE_NAME: "adi_imu"

permissions:
  contents: read
  checks: write

jobs:
  ament_lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          # Humble Hawksbill (May 2022 - May 2027) - Ubuntu 22.04 (Jammy)
          - humble
        linter:
          - copyright
          - pep257
          - xmllint
          - cppcheck
          - lint_cmake

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@649ef6bcd696da05bc27ceb3fab69d810c0daeab # v0.7.19
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
          use-ros2-testing: false

      - name: Run Linter
        env:
          AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: 1
        uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          distribution: ${{ matrix.ros_distribution }}
          package-name: ${{ env.PACKAGE_NAME }}
          arguments: |
            ${{ matrix.linter == 'cppcheck' && ' --language=c++ ' || '' }}

  formatting-check:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run clang-format style check
      uses: jidicula/clang-format-action@654a770daa28443dd111d133e4083e21c1075674 # v4.18.0
      with:
        clang-format-version: '14'
